import { MEDIA } from './media';

export interface Product {
  id: string;
  name: string;
  category: 'Eggs' | 'Poultry' | 'Feeds' | 'Ghanaian Foods';
  price: number | null;
  unit: string;
  image: string;
  tagline: string;
  features: string[];
}

export const products: Product[] = [
  {
    id: 'fresh-eggs',
    name: 'Fresh Eggs',
    category: 'Eggs',
    price: 25,
    unit: 'tray (30 eggs)',
    image: MEDIA.freshEggs,
    tagline: 'Farm-fresh daily',
    features: [
      'Collected same-day',
      'Grade A quality',
      'Free-range hens',
      'Unwashed & natural',
      'Rich golden yolks',
    ],
  },
  {
    id: 'crate-eggs',
    name: 'Crate of Eggs',
    category: 'Eggs',
    price: null,
    unit: 'crate (360 eggs)',
    image: MEDIA.crateEggs,
    tagline: 'Bulk supply for businesses',
    features: [
      '360 eggs per crate',
      'Wholesale pricing',
      'Regular delivery available',
      'Grade A certified',
      'Ideal for hotels & caterers',
    ],
  },
  {
    id: 'live-broiler',
    name: 'Live Broiler Chickens',
    category: 'Poultry',
    price: 45,
    unit: 'bird',
    image: MEDIA.broilerChicken,
    tagline: 'Healthy, farm-raised birds',
    features: [
      '6–8 weeks maturity',
      'Avg. weight 2.5–3.5 kg',
      'Antibiotic-free diet',
      'Vaccinated flock',
      'Bulk orders available',
    ],
  },
  {
    id: 'dressed-broiler',
    name: 'Dressed Broiler Chickens',
    category: 'Poultry',
    price: 60,
    unit: 'bird',
    image: MEDIA.dressedChicken,
    tagline: 'Ready for the kitchen',
    features: [
      'Cleaned & eviscerated',
      'Same-day processing',
      'No preservatives',
      'Chilled or fresh',
      'Custom cuts on request',
    ],
  },
  {
    id: 'layer-chickens',
    name: 'Layer Chickens',
    category: 'Poultry',
    price: 35,
    unit: 'bird',
    image: MEDIA.layerChickens,
    tagline: 'High-yield laying hens',
    features: [
      'Started pullets available',
      'Up to 300 eggs/year',
      'Proven breed lines',
      'Vaccinated & healthy',
      'Small & large flocks',
    ],
  },
  {
    id: 'day-old-chicks',
    name: 'Day-Old Chicks',
    category: 'Poultry',
    price: 8,
    unit: 'chick',
    image: MEDIA.dayOldChicks,
    tagline: 'Start your flock right',
    features: [
      'Broiler & layer breeds',
      'Vaccinated at hatch',
      'Sex-sorted on request',
      'Supplied with starter guide',
      'Minimum order: 50 chicks',
    ],
  },
  {
    id: 'layer-starter',
    name: 'Layer Starter Feed',
    category: 'Feeds',
    price: 180,
    unit: '50kg bag',
    image: MEDIA.layerStarter,
    tagline: 'Optimal nutrition from day one',
    features: [
      '18–20% crude protein',
      'Medicated formulation',
      'Weeks 0–8',
      'Supports bone development',
      'Locally milled',
    ],
  },
  {
    id: 'broiler-starter',
    name: 'Broiler Starter Feed',
    category: 'Feeds',
    price: 195,
    unit: '50kg bag',
    image: MEDIA.broilerStarter,
    tagline: 'Fast growth, healthy birds',
    features: [
      '22–24% crude protein',
      'High energy formula',
      'Weeks 0–4',
      'FCR optimised',
      'No hormones added',
    ],
  },
  {
    id: 'grower-mash',
    name: 'Grower Mash',
    category: 'Feeds',
    price: 170,
    unit: '50kg bag',
    image: MEDIA.growerMash,
    tagline: 'Sustained growth phase feed',
    features: [
      '16–18% crude protein',
      'Balanced minerals',
      'Weeks 4–8',
      'Mash texture',
      'Cost-effective formula',
    ],
  },
  {
    id: 'ghanaian-yam',
    name: 'Premium Ghanaian Yams',
    category: 'Ghanaian Foods',
    price: null,
    unit: 'bulk / container',
    image: MEDIA.ghanaianYam,
    tagline: 'Export-grade, UK & EU ready',
    features: [
      'Puna & Dente varieties',
      'EU import certified',
      'Custom pack sizes',
      'High dry-matter content',
      'Long shelf life',
    ],
  },
  {
    id: 'sweet-corn',
    name: 'Sweet Corn',
    category: 'Ghanaian Foods',
    price: null,
    unit: 'bulk',
    image: MEDIA.sweetCorn,
    tagline: 'Peak-harvest sweetness',
    features: [
      'Harvested at peak ripeness',
      'Export-ready packaging',
      'Air-freighted fresh',
      'Minimum 1 tonne orders',
      'Phytosanitary certified',
    ],
  },
  {
    id: 'soybeans',
    name: 'Soybeans',
    category: 'Ghanaian Foods',
    price: null,
    unit: 'bulk',
    image: MEDIA.soybeans,
    tagline: 'High-protein commodity grade',
    features: [
      '38–42% protein content',
      'Non-GMO sourced',
      'Cleaned & graded',
      'Bulk container loads',
      'Phytosanitary certified',
    ],
  },
];
